/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "on-tertiary-fixed": "#2a1700",
                "surface-bright": "#f8f9ff",
                "on-secondary": "#ffffff",
                "surface-dim": "#cbdbf5",
                "surface-container": "#e5eeff",
                "on-primary": "#ffffff",
                "secondary-fixed": "#6ffbbe",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed-dim": "#ffb95f",
                tertiary: "#684000",
                "inverse-primary": "#c3c0ff",
                "on-primary-container": "#dad7ff",
                "surface-container-low": "#eff4ff",
                secondary: "#006c49",
                "primary-fixed-dim": "#c3c0ff",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#464555",
                error: "#ba1a1a",
                "primary-fixed": "#e2dfff",
                "inverse-on-surface": "#eaf1ff",
                "on-primary-fixed": "#0f0069",
                "on-secondary-fixed": "#002113",
                "on-secondary-container": "#00714d",
                "outline-variant": "#c7c4d8",
                "surface-tint": "#4d44e3",
                "secondary-fixed-dim": "#4edea3",
                primary: "#3525cd",
                "tertiary-fixed": "#ffddb8",
                background: "#f8f9ff",
                "surface-variant": "#d3e4fe",
                "on-error": "#ffffff",
                "on-tertiary-container": "#ffd4a4",
                "error-container": "#ffdad6",
                "on-surface": "#0b1c30",
                "surface-container-highest": "#d3e4fe",
                "on-error-container": "#93000a",
                "surface-container-high": "#dce9ff",
                "on-secondary-fixed-variant": "#005236",
                "tertiary-container": "#885500",
                "primary-container": "#4f46e5",
                surface: "#f8f9ff",
                "inverse-surface": "#213145",
                "on-primary-fixed-variant": "#3323cc",
                "on-tertiary-fixed-variant": "#653e00",
                outline: "#777587",
                "on-background": "#0b1c30",
                "secondary-container": "#6cf8bb",
            },
            borderRadius: {
                DEFAULT: "0.25rem",
                lg: "0.5rem",
                xl: "0.75rem",
                full: "9999px",
            },
            spacing: {
                base: "8px",
                "stack-md": "12px",
                "container-max": "1200px",
                "stack-lg": "24px",
                "gutter-desktop": "24px",
                "gutter-mobile": "16px",
                "stack-sm": "4px",
            },
            fontFamily: {
                "headline-md": ["Geist"],
                "label-md": ["Geist"],
                "label-sm": ["Geist"],
                "body-md": ["Geist"],
                "headline-lg": ["Geist"],
                "headline-lg-mobile": ["Geist"],
                "body-lg": ["Geist"],
            },
            fontSize: {
                "headline-md": [
                    "20px",
                    {
                        lineHeight: "28px",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "label-md": [
                    "12px",
                    {
                        lineHeight: "16px",
                        letterSpacing: "0.02em",
                        fontWeight: "500",
                    },
                ],
                "label-sm": [
                    "11px",
                    {
                        lineHeight: "14px",
                        letterSpacing: "0.03em",
                        fontWeight: "500",
                    },
                ],
                "body-md": [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0",
                        fontWeight: "400",
                    },
                ],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "headline-lg-mobile": [
                    "24px",
                    {
                        lineHeight: "32px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "body-lg": [
                    "16px",
                    {
                        lineHeight: "24px",
                        letterSpacing: "0",
                        fontWeight: "400",
                    },
                ],
            },
        },
    },
};
