/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                // Light theme colors (existing)
                "on-tertiary-fixed": "#2a1700",
                "surface-bright": "#f8f9ff",
                "on-secondary": "#ffffff",
                "surface-dim": "#cbdbf5",
                "surface-container": "#e5eeff",
                "on-primary": "#ffffff",
                "secondary-fixed": "#6ffbbe",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed-dim": "#ffb95f",
                tertiary: "#684000",
                "inverse-primary": "#c3c0ff",
                "on-primary-container": "#dad7ff",
                "surface-container-low": "#eff4ff",
                secondary: "#006c49",
                "primary-fixed-dim": "#c3c0ff",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#464555",
                error: "#ba1a1a",
                "primary-fixed": "#e2dfff",
                "inverse-on-surface": "#eaf1ff",
                "on-primary-fixed": "#0f0069",
                "on-secondary-fixed": "#002113",
                "on-secondary-container": "#00714d",
                "outline-variant": "#c7c4d8",
                "surface-tint": "#4d44e3",
                "secondary-fixed-dim": "#4edea3",
                primary: "#3525cd",
                "tertiary-fixed": "#ffddb8",
                background: "#f8f9ff",
                "surface-variant": "#d3e4fe",
                "on-error": "#ffffff",
                "on-tertiary-container": "#ffd4a4",
                "error-container": "#ffdad6",
                "on-surface": "#0b1c30",
                "surface-container-highest": "#d3e4fe",
                "on-error-container": "#93000a",
                "surface-container-high": "#dce9ff",
                "on-secondary-fixed-variant": "#005236",
                "tertiary-container": "#885500",
                "primary-container": "#4f46e5",
                surface: "#f8f9ff",
                "inverse-surface": "#213145",
                "on-primary-fixed-variant": "#3323cc",
                "on-tertiary-fixed-variant": "#653e00",
                outline: "#777587",
                "on-background": "#0b1c30",
                "secondary-container": "#6cf8bb",

                // Dark theme colors (from spec)
                dark: {
                    surface: "#0b1326",
                    "surface-dim": "#0b1326",
                    "surface-bright": "#31394d",
                    "surface-container-lowest": "#060e20",
                    "surface-container-low": "#131b2e",
                    "surface-container": "#171f33",
                    "surface-container-high": "#222a3d",
                    "surface-container-highest": "#2d3449",
                    "on-surface": "#dae2fd",
                    "on-surface-variant": "#c7c4d7",
                    "inverse-surface": "#dae2fd",
                    "inverse-on-surface": "#283044",
                    outline: "#908fa0",
                    "outline-variant": "#464554",
                    "surface-tint": "#c0c1ff",
                    primary: "#c0c1ff",
                    "on-primary": "#1000a9",
                    "primary-container": "#8083ff",
                    "on-primary-container": "#0d0096",
                    "inverse-primary": "#494bd6",
                    secondary: "#b9c8de",
                    "on-secondary": "#233143",
                    "secondary-container": "#39485a",
                    "on-secondary-container": "#a7b6cc",
                    tertiary: "#ffb783",
                    "on-tertiary": "#4f2500",
                    "tertiary-container": "#d97721",
                    "on-tertiary-container": "#452000",
                    error: "#ffb4ab",
                    "on-error": "#690005",
                    "error-container": "#93000a",
                    "on-error-container": "#ffdad6",
                    "primary-fixed": "#e1e0ff",
                    "primary-fixed-dim": "#c0c1ff",
                    "on-primary-fixed": "#07006c",
                    "on-primary-fixed-variant": "#2f2ebe",
                    "secondary-fixed": "#d4e4fa",
                    "secondary-fixed-dim": "#b9c8de",
                    "on-secondary-fixed": "#0d1c2d",
                    "on-secondary-fixed-variant": "#39485a",
                    "tertiary-fixed": "#ffdcc5",
                    "tertiary-fixed-dim": "#ffb783",
                    "on-tertiary-fixed": "#301400",
                    "on-tertiary-fixed-variant": "#703700",
                    background: "#0b1326",
                    "on-background": "#dae2fd",
                    "surface-variant": "#2d3449",
                },
            },
            borderRadius: {
                sm: "0.25rem",
                DEFAULT: "0.5rem",
                md: "0.75rem",
                lg: "1rem",
                xl: "1.5rem",
                full: "9999px",
            },
            spacing: {
                unit: "4px",
                gutter: "24px",
                "margin-desktop": "64px",
                "margin-mobile": "16px",
                "container-max": "1280px",
                base: "8px",
                "stack-md": "12px",
                "stack-lg": "24px",
                "gutter-desktop": "24px",
                "gutter-mobile": "16px",
                "stack-sm": "4px",
            },
            fontFamily: {
                "headline-md": ["Geist"],
                "label-md": ["Geist"],
                "label-sm": ["Geist"],
                "body-md": ["Geist"],
                "headline-lg": ["Geist"],
                "headline-lg-mobile": ["Geist"],
                "body-lg": ["Geist"],
                display: ["Geist"],
                code: ["Geist"],
            },
            fontSize: {
                display: [
                    "56px",
                    {
                        lineHeight: "64px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "headline-lg": [
                    "32px",
                    {
                        lineHeight: "40px",
                        letterSpacing: "-0.01em",
                        fontWeight: "600",
                    },
                ],
                "headline-lg-mobile": [
                    "28px",
                    {
                        lineHeight: "36px",
                        letterSpacing: "-0.02em",
                        fontWeight: "600",
                    },
                ],
                "headline-md": [
                    "24px",
                    {
                        lineHeight: "32px",
                        fontWeight: "500",
                    },
                ],
                "body-lg": [
                    "18px",
                    {
                        lineHeight: "28px",
                        letterSpacing: "0",
                        fontWeight: "400",
                    },
                ],
                "body-md": [
                    "16px",
                    {
                        lineHeight: "24px",
                        letterSpacing: "0",
                        fontWeight: "400",
                    },
                ],
                "label-md": [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0.01em",
                        fontWeight: "500",
                    },
                ],
                code: [
                    "14px",
                    {
                        lineHeight: "20px",
                        letterSpacing: "0",
                        fontWeight: "400",
                    },
                ],
                "label-sm": [
                    "11px",
                    {
                        lineHeight: "14px",
                        letterSpacing: "0.03em",
                        fontWeight: "500",
                    },
                ],
            },
        },
    },
};
